export const cartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  ADD_CART: "ADD_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  INCREASE_ITEM: "INCREASE_ITEM",
  DECREASE_ITEM: "DECREASE_ITEM",
  CLEAR_CART: "CLEAR_CART",
};
